### ISSUE TITLE
AttributeError: module 'distutils' has no attribute 'version'

### ISSUE THREAD

**Issue by xiaogaoyaoiris** [BUAABIGSCity/PDFormer#4]
Thanks for your excellent job.  When running run_model.py, an error occured as below. Could ypu please help to fix this?

Traceback (most recent call last):
  File "/home/gy/PDFormer/libcity/utils/utils.py", line 11, in get_executor
    return getattr(importlib.import_module('libcity.executor'),
  File "/usr/local/anaconda3/envs/pdformer/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/gy/PDFormer/libcity/executor/__init__.py", line 1, in <module>
    from libcity.executor.traffic_state_executor import TrafficStateExecutor
  File "/home/gy/PDFormer/libcity/executor/traffic_state_executor.py", line 8, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/usr/local/anaconda3/envs/pdformer/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gy/PDFormer/run_model.py", line 52, in <module>
    run_model(task=args.task, model_name=args.model, dataset_name=args.dataset,
  File "/home/gy/PDFormer/libcity/pipeline/pipeline.py", line 44, in run_model
    executor = get_executor(config, model)
  File "/home/gy/PDFormer/libcity/utils/utils.py", line 14, in get_executor
    raise AttributeError('executor is not found')
AttributeError: executor is not found

**Comment by aptx1231** [comment]
你好，这个应该不是代码的问题，是环境的问题，参考：https://blog.csdn.net/hahhahahhaja/article/details/128003170

setuptools               58.0.4
torch                    1.10.2
这个是我这边的环境，你看看可以参考一下

**Comment by xiaogaoyaoiris** [comment]
谢谢大佬！
