### ISSUE TITLE
ValueError: Not found .geo file!

### ISSUE THREAD

**Issue by ry123scuer** [BUAABIGSCity/PDFormer#43]
Traceback (most recent call last):
  File "/home/ren/公共的/ry/PDFormer-master/libcity/data/utils.py", line 13, in get_dataset
    return getattr(importlib.import_module('libcity.data.dataset'),
  File "/home/ren/公共的/ry/PDFormer-master/libcity/data/dataset/pdformer_dataset.py", line 14, in __init__
    super().__init__(config)
  File "/home/ren/公共的/ry/PDFormer-master/libcity/data/dataset/traffic_state_point_dataset.py", line 9, in __init__
    super().__init__(config)
  File "/home/ren/公共的/ry/PDFormer-master/libcity/data/dataset/traffic_state_datatset.py", line 75, in __init__
    raise ValueError('Not found .geo file!')
ValueError: Not found .geo file!
我找到了报错的代码：
        if os.path.exists(self.data_path + self.geo_file + '.geo'):
            self._load_geo()
        else:
            raise ValueError('Not found .geo file!')
        if os.path.exists(self.data_path + self.rel_file + '.rel'):
            self._load_rel()
        else:
            self.adj_mx = np.zeros((len(self.geo_ids), len(self.geo_ids)), dtype=np.float32)

这个geo_file和rel_file到底是啥，说是应该放在raw_data的PeMS04下面，我看了下dataset_cache下面的文件，好像也不太像，能不能看下你们的raw_data目录。
期待你们的回复，谢谢！

**Comment by ry123scuer** [comment]
已解决，原来是因为我没有用作者的链接下载数据集
